### ISSUE TITLE
Chapter 8 - spinner and waiter apps

### ISSUE THREAD

**Issue by kalganem** [hadley/mastering-shiny#418] opened 2021-02-19 13:38 UTC
Hi,

In chapter 8.3.2 and 8.3.3, These apps failed to run:

https://hadley.shinyapps.io/ms-spinner-1/
https://hadley.shinyapps.io/ms-spinner-2/
https://hadley.shinyapps.io/ms-waiter/

<img width="591" alt="Screen Shot 2021-02-19 at 8 34 41 AM" src="https://user-images.githubusercontent.com/37287792/108511083-61b2e000-728d-11eb-9448-0365e446a2da.png">

**Comment by hadley** [comment] 2021-02-19 22:20
Duplicate of #406 — there's no way for you to know that, but I do 😄

**Closed by hadley** 2021-02-19 22:20 UTC
