### ISSUE TITLE
Example in 10.1.2 is not working

### ISSUE THREAD

**Issue by kitmacleod** [hadley/mastering-shiny#382] opened 2021-02-03 08:29 UTC
https://hadley.shinyapps.io/ms-update-nested/

Error in value[[3L]](cond) : there is no package called ‘dplyr’
Calls: local ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted

**Comment by hadley** [comment] 2021-02-08 14:36
Duplicate of #357

**Closed by hadley** 2021-02-08 14:36 UTC
